### ISSUE TITLE
Experiencing cursor flicker

### ISSUE THREAD

**Issue by archiif** [io12/good-scroll.el#29]
**Describe the bug**
Scrolling causes cursor to flicker

**To Reproduce**
1. Scroll to any direction
2. Cursor flickers

**Expected behavior**
Cursor doesn't flicker

**Videos**
I tried to record it several times, but for some reason I just can't capture the flicker in the video (or rather the flicker does not look as severe as it actually is), I'm guessing it has something to do with the framerate.

**Version and environment**
 - OS: Windows 10 (MinGW-w64)
 - Emacs version: 28.0.92

**Additional context**
I'm using evil-mode.

**Comment by archiif** [comment]
I managed to capture it somewhat:
![2022-05-05_06-54-23](https://user-images.githubusercontent.com/60074051/166843311-ca2e1d18-9efd-4781-a797-fd2ff7a3936e.gif)

**Comment by io12** [comment]
Sorry I didn't look into this until now. I can't reproduce this on Linux. I can _sort of_ reproduce it in a Windows 10 VM with MinGW-w64, but it's not as bad for me as your screencast makes it seem. I don't think this is a problem with good-scroll, because similar issues happened for me even when good-scroll is disabled. For example here is a screencast of scrolling by just moving the cursor around:

[Screencast from 07-09-2022 01:46:00 AM.webm](https://user-images.githubusercontent.com/7348004/178093806-7f4145a5-e0db-4ac7-a435-f2151a00c3f9.webm)

So it might not be good-scroll's fault, but a bug in Emacs's Windows GUI. Can you reproduce the flickering when scrolling by moving the cursor, like by scrolling to the top of a buffer by holding the up arrow to move the cursor up?

**Comment by archiif** [comment]
I upgraded to emacs 29, which introduces double-buffering for Windows, so flickers in general are no longer an issue.
